export const TEXT = {
  CREATEVARIABLE: 'VARS',
  SERVICENAME: 'SERVICE NAME',
  DATABASEACCESS: 'DATABASE ACCESS',
  APIPUBLIC: 'API PUBLIC',
  VARIABLENAME: 'VARIABLE NAME',
  PRODUCTIONVALUE: 'PRODUCTION VALUE',
  BETAVALUE: 'BETA VALUE',
  ADDVARIABLE: 'ADD VARIABLE',
  SAVE: 'SAVE',
}
