export const {
  REACT_APP_BITBUCKET_AUTHORIZE_URL,
  REACT_APP_BITBUCKET_CLIENT_ID,
  REACT_APP_BITBUCKET_REDIRECT_URI,
  REACT_APP_BITBUCKET_SCOPE,
  REACT_APP_BITBUCKET_RESPONSE_TYPE,
} = process.env

export const TEXT = {
  FOOTER: '© 2024 Alintra. Todos os direitos reservados.',
  TITLE: 'BITBUCKET',
  BUTTON: 'BITBUCKET SSO',
  AUTHORIZED: 'User not authorized',
}
