export const TEXT = {
  LABEL_PACKAGE_NAME: 'NAME',
  LABEL_RUN_PACKAGE: 'RUN CMD',
  PRESET_PACKAGE: '@alintra/',
  LABEL_NPM_PACKAGE: 'npm install ',
  LABEL_URL_BITBUCKET: 'https://bitbucket.org/allintra/package#',
  LABEL_BETA_VALUE: 'BETA VALUE',
  BUTTON_ADD_VARIABLE: 'ADD VARIABLE',
  BUTTON_SAVE: 'SAVE',
  BUTTON_CLOSE: 'CLOSE',
}
