export const TEXT = {
  DASHBOARD: 'DASHBOARD',
  SERVICES: 'SERVICES',
  CREATESERVICE: 'CREATE SERVICE',
  VARIABLES: 'VARIABLES',
  PACKAGES: 'PACKAGES',
  CREATEPACKAGE: 'CREATE PACKAGE',
  LOGOUT: 'LOGOUT',
}
